apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: survey-worker
  template:
    metadata:
      labels:
        app: survey-worker
    spec:
      containers:
      - name: worker
        image: <your-ecr-repository-url>/survey-app:latest
        command: ["node", "src/worker.js"]
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          value: survey_db
        - name: POSTGRES_HOST
          value: postgres 